"use client";
/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-unused-vars */

import { useEffect, useMemo, useState } from "react";
import rawData from "@/app/data/platform-data.json";
import { DetailedCompare, DetailedFinder, DetailedPhones } from "@/app/components/DetailedWorkspaces";
import { DetailedReviews } from "@/app/components/DetailedReviews";
import { IntelligenceWorkspace } from "@/app/components/IntelligenceWorkspace";
import { ActionCenter } from "@/app/components/ActionCenter";

type Mode = "overview" | "phones" | "reviews" | "finder" | "compare" | "intelligence" | "actions";
type Phone = (typeof rawData.phones)[number];
type FinderPhone = (typeof rawData.finder.overall)[number];
function Link({ href, className, children }: { href: string; className?: string; children: React.ReactNode }) { return <a href={href} className={className}>{children}</a>; }
const money = (value: number | null) => value ? `₹${Math.round(value).toLocaleString("en-IN")}` : "Price unavailable";
const pct = (value: number | null | undefined) => `${Number(value || 0).toFixed(1)}%`;

function WorkspaceHeader({ eyebrow, title, summary, meta }: { eyebrow: string; title: string; summary: string; meta: string }) {
  return <header className="workspace-header"><div><span className="section-kicker">{eyebrow}</span><h1>{title}</h1><p>{summary}</p></div><div className="workspace-meta"><i /><span>Research snapshot</span><small>{meta}</small></div></header>;
}
function MetricCard({ label, value, detail, tone = "cyan" }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`metric-card ${tone}`}><span className="metric-label">{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function ScoreBar({ value, tone = "cyan" }: { value: number; tone?: string }) { return <div className={`score-track ${tone}`} aria-label={`${value.toFixed(1)} percent`}><i style={{ width: `${Math.max(2, Math.min(100, value))}%` }} /></div>; }
function EvidenceBadge({ score }: { score: number }) { const label = score >= 75 ? "High evidence" : score >= 50 ? "Moderate evidence" : "Limited evidence"; return <span className={`evidence-badge ${score >= 75 ? "high" : score >= 50 ? "medium" : "low"}`}>{label}</span>; }
function Signal({ label, value, detail, positive = false }: { label: string; value: string; detail: string; positive?: boolean }) { return <div className="signal-row"><span className={`signal-icon ${positive ? "positive" : "negative"}`}>{positive ? "+" : "−"}</span><span><small>{label}</small><strong>{value}</strong></span><em>{detail}</em></div>; }

function Overview() {
  const { metrics, signals, brief } = rawData.overview;
  return <><section className="hero-grid"><div className="hero-copy"><div className="live-label"><i /> India smartphone market · research snapshot</div><h1>The market is speaking.<br /><em>Here&apos;s what it says.</em></h1><p>Evidence-backed product intelligence built from customer reviews, specifications, prices and competitive signals—not guesswork.</p><div className="hero-actions"><Link className="primary-action" href="/intelligence">Explore intelligence <span>↗</span></Link><Link className="secondary-action" href="/reviews">Inspect customer evidence</Link></div></div><aside className="market-orbit" aria-label="Current market signal"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-center"><span>Market signal</span><strong>{metrics.positive_percent}</strong><small>review-weighted positive</small></div><div className="orbit-label label-a"><i /> {metrics.brands} brands</div><div className="orbit-label label-b"><i /> {metrics.reviews.toLocaleString()} reviews</div><div className="orbit-label label-c"><i /> {metrics.phones} phones</div></aside></section><section className="metric-grid"><MetricCard label="Products monitored" value={String(metrics.phones)} detail={`${metrics.catalog_brands} catalog brands · ${metrics.brands} with reviews`} /><MetricCard label="Customer evidence" value={metrics.reviews.toLocaleString()} detail={`${metrics.usable_reviews.toLocaleString()} usable reviews`} tone="violet" /><MetricCard label="Positive signal" value={pct(metrics.positive_percent)} detail="Review-weighted across the market" tone="green" /><MetricCard label="Aspect observations" value={metrics.aspects.toLocaleString()} detail="Evidence grouped by topic" tone="amber" /></section><section className="intelligence-grid"><article className="brief-panel"><div className="panel-heading"><div><span className="section-kicker">Executive readout</span><h2>What deserves attention now</h2></div><span className="confidence">High confidence</span></div><p className="brief-copy">{brief}</p><div className="evidence-note"><span>Evidence basis</span> {metrics.usable_reviews.toLocaleString()} usable reviews · Amazon + Flipkart</div></article><aside className="signal-panel"><div className="panel-heading compact"><div><span className="section-kicker">Signal board</span><h2>Market now</h2></div><Link className="quiet-link" href="/intelligence">View all</Link></div><div className="signal-list"><Signal label="Most loved" value={signals.strongest_aspect} detail={`${signals.strongest_mentions.toLocaleString()} positive mentions`} positive /><Signal label="Primary friction" value={signals.primary_friction} detail={`${signals.friction_mentions.toLocaleString()} negative mentions`} /><Signal label="Sentiment leader" value={signals.sentiment_leader} detail={`${pct(signals.leader_positive)} positive signal`} positive /></div></aside></section></>;
}

function Phones() {
  const brands = ["All", ...Array.from(new Set(rawData.phones.map((phone) => phone.brand))).sort()];
  const [brand, setBrand] = useState("All"); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(rawData.phones[0].phone_id);
  useEffect(() => { const timer = window.setTimeout(() => { const requested = new URLSearchParams(window.location.search).get("phone"); if (requested && rawData.phones.some((phone) => phone.phone_id === requested)) setSelectedId(requested); }, 0); return () => window.clearTimeout(timer); }, []);
  const results = useMemo(() => rawData.phones.filter((phone) => (brand === "All" || phone.brand === brand) && `${phone.phone_name} ${phone.brand}`.toLowerCase().includes(query.toLowerCase())).slice(0, 16), [brand, query]);
  const selected = rawData.phones.find((phone) => phone.phone_id === selectedId) || results[0] || rawData.phones[0];
  return <><WorkspaceHeader eyebrow="Product explorer" title="Every phone. One evidence layer." summary="Move from market landscape to product truth without losing the reviews behind each signal." meta={`${rawData.phones.length} products indexed`} /><section className="filter-ribbon"><label className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search product or brand" /></label><div className="chip-scroll" aria-label="Brand filters">{brands.map((item) => <button className={brand === item ? "filter-chip active" : "filter-chip"} key={item} onClick={() => setBrand(item)}>{item}</button>)}</div></section><section className="explorer-layout"><div className="product-grid">{results.map((phone) => <PhoneCard key={phone.phone_id} phone={phone} active={phone.phone_id === selected.phone_id} onSelect={() => setSelectedId(phone.phone_id)} />)}{!results.length && <p className="empty-state">No phones match those filters.</p>}</div><ProductBrief phone={selected} /></section></>;
}
function PhoneCard({ phone, active, onSelect }: { phone: Phone; active: boolean; onSelect: () => void }) { return <button className={active ? "phone-card active" : "phone-card"} onClick={onSelect} type="button"><div className="phone-image-wrap">{phone.image_url ? <img src={phone.image_url} alt="" /> : <span>{phone.brand.slice(0, 1)}</span>}</div><div className="phone-card-copy"><small>{phone.brand} · {phone.segment_label}</small><strong>{phone.phone_name}</strong><span>{money(phone.best_price)}</span></div><div className="phone-score"><strong>{phone.positive_percent.toFixed(0)}</strong><small>positive</small></div></button>; }
function ProductBrief({ phone }: { phone: Phone }) { return <aside className="product-brief"><div className="product-hero"><div><span className="section-kicker">Selected product</span><h2>{phone.phone_name}</h2><p>{phone.consumer_verdict || "Customer evidence is still developing for this product."}</p></div><EvidenceBadge score={phone.evidence_score} /></div><div className="brief-score"><div><small>Positive signal</small><strong>{pct(phone.positive_percent)}</strong></div><ScoreBar value={phone.positive_percent} tone="green" /></div><div className="spec-grid"><Spec label="Recorded price" value={money(phone.best_price)} /><Spec label="Evidence" value={`${phone.review_count} reviews`} /><Spec label="Processor" value={phone.processor || "—"} /><Spec label="Battery" value={phone.battery || "—"} /><Spec label="RAM" value={phone.ram || "—"} /><Spec label="Display" value={phone.display || "—"} /></div><div className="insight-columns"><div><small>What lands well</small>{phone.strengths.slice(0, 3).map((item) => <span className="insight-pill good" key={item}>+ {item}</span>)}</div><div><small>Watch closely</small>{phone.pain_points.slice(0, 3).map((item) => <span className="insight-pill risk" key={item}>− {item}</span>)}</div></div><Link href={`/compare?left=${encodeURIComponent(phone.phone_id)}`} className="full-action">Compare this product <span>↗</span></Link></aside>; }
function Spec({ label, value }: { label: string; value: string }) { return <div className="spec-cell"><small>{label}</small><strong>{value}</strong></div>; }

function Reviews() {
  const [query, setQuery] = useState(""); const [platform, setPlatform] = useState("All"); const [signal, setSignal] = useState("All");
  const reviews = useMemo(() => rawData.reviews.filter((review) => (platform === "All" || review.platform === platform) && (signal === "All" || review.signal === signal.toLowerCase()) && `${review.review_text} ${review.phone_name} ${review.brand}`.toLowerCase().includes(query.toLowerCase())).slice(0, 18), [query, platform, signal]);
  return <><WorkspaceHeader eyebrow="Customer evidence" title="Read the signal at source." summary="Search the actual voice of the customer, then trace each theme back to the product and marketplace it came from." meta="2,860 usable reviews" /><section className="filter-ribbon wrap"><label className="search-field wide"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search review text, phone, or brand" /></label><Segmented items={["All", "Amazon", "Flipkart"]} active={platform} onChange={setPlatform} /><Segmented items={["All", "Positive", "Mixed", "Risk"]} active={signal} onChange={setSignal} /></section><div className="results-line"><span>{reviews.length} high-information reviews shown</span><span>Sorted by evidence density</span></div><section className="review-grid">{reviews.map((review) => <article className="review-card" key={review.review_id}><div className="review-top"><span className={`signal-dot ${review.signal}`} /><span>{review.signal}</span><em>{review.platform}</em></div><blockquote>“{review.review_text}”</blockquote><div className="review-foot"><span><strong>{review.phone_name}</strong><small>{review.brand}</small></span><span><strong>{review.word_count}</strong><small>words</small></span></div></article>)}</section></>;
}
function Segmented({ items, active, onChange }: { items: string[]; active: string; onChange: (value: string) => void }) { return <div className="segmented">{items.map((item) => <button key={item} className={active === item ? "active" : ""} onClick={() => onChange(item)}>{item}</button>)}</div>; }

function Finder() {
  const useCases = Object.keys(rawData.finder) as Array<keyof typeof rawData.finder>; const [useCase, setUseCase] = useState<keyof typeof rawData.finder>("overall"); const [budget, setBudget] = useState(50000);
  const results = rawData.finder[useCase].filter((phone) => phone.best_price && phone.best_price <= budget).slice(0, 8);
  return <><WorkspaceHeader eyebrow="Decision engine" title="Find the phone that fits the job." summary="Transparent rankings combine sentiment, use-case evidence, complaint safety and confidence—not a mystery recommendation." meta="Explainable weighted scoring" /><section className="finder-controls"><div><small>What matters most?</small><div className="usecase-tabs">{useCases.map((item) => <button className={useCase === item ? "active" : ""} key={item} onClick={() => setUseCase(item)}>{item}</button>)}</div></div><div className="budget-control"><span><small>Maximum budget</small><strong>{money(budget)}</strong></span><input type="range" min="8000" max="50000" step="1000" value={budget} onChange={(event) => setBudget(Number(event.target.value))} aria-label="Maximum budget" /></div></section><section className="ranking-list">{results.map((phone, index) => <RankingRow key={phone.phone_id} phone={phone} rank={index + 1} />)}{!results.length && <p className="empty-state">No evidence-backed matches sit inside this budget yet.</p>}</section><p className="method-note"><strong>How this works:</strong> 38% product sentiment · 32% use-case fit · 16% complaint safety · 14% evidence confidence. Every score is inspectable.</p></>;
}
function RankingRow({ phone, rank }: { phone: FinderPhone; rank: number }) { return <article className="ranking-row"><span className="rank-number">{String(rank).padStart(2, "0")}</span><div className="rank-product"><div className="mini-phone">{phone.image_url && <img src={phone.image_url} alt="" />}</div><span><small>{phone.brand} · {money(phone.best_price)}</small><strong>{phone.phone_name}</strong><em>{phone.reason}</em></span></div><div className="rank-components"><MiniScore label="Sentiment" value={phone.score.sentiment} /><MiniScore label="Use-case fit" value={phone.score.aspect_fit} /><MiniScore label="Safety" value={phone.score.complaint_safety} /></div><div className="rank-score"><strong>{phone.score.overall}</strong><small>fit score</small></div><a href={`/compare?left=${encodeURIComponent(phone.phone_id)}`}>Compare ↗</a></article>; }
function MiniScore({ label, value }: { label: string; value: number }) { return <span><small>{label}</small><ScoreBar value={value} /><em>{value.toFixed(0)}</em></span>; }

function Compare() {
  const scored = rawData.finder.overall; const [leftId, setLeftId] = useState(scored[0].phone_id); const [rightId, setRightId] = useState(scored[1].phone_id); const left = scored.find((phone) => phone.phone_id === leftId) || scored[0]; const right = scored.find((phone) => phone.phone_id === rightId) || scored[1]; const winner = left.score.overall >= right.score.overall ? left : right;
  useEffect(() => { const timer = window.setTimeout(() => { const requested = new URLSearchParams(window.location.search).get("left"); if (requested && scored.some((phone) => phone.phone_id === requested)) setLeftId(requested); }, 0); return () => window.clearTimeout(timer); }, [scored]);
  return <><WorkspaceHeader eyebrow="Head-to-head" title="Make the trade-off visible." summary="Compare products on the same evidence scale, from customer sentiment to complaint risk and use-case fit." meta="Five comparable dimensions" /><section className="compare-pickers"><PhonePicker label="Product A" value={leftId} onChange={setLeftId} phones={scored} /><button className="swap-button" onClick={() => { setLeftId(rightId); setRightId(leftId); }} aria-label="Swap compared phones">⇄</button><PhonePicker label="Product B" value={rightId} onChange={setRightId} phones={scored} /></section><section className="verdict-banner"><span>Evidence-backed verdict</span><strong>{winner.phone_name} has the stronger overall profile.</strong><p>A {Math.abs(left.score.overall - right.score.overall).toFixed(1)} point gap based on the same transparent scoring model.</p></section><section className="comparison-grid"><CompareProduct phone={left} winner={winner.phone_id === left.phone_id} /><div className="comparison-axis"><span>Overall fit</span><span>Sentiment</span><span>Use-case fit</span><span>Complaint safety</span><span>Evidence</span><span>Review volume</span><span>Recorded price</span></div><CompareProduct phone={right} winner={winner.phone_id === right.phone_id} /></section></>;
}
function PhonePicker({ label, value, onChange, phones }: { label: string; value: string; onChange: (value: string) => void; phones: FinderPhone[] }) { return <label className="phone-picker"><small>{label}</small><select value={value} onChange={(event) => onChange(event.target.value)}>{phones.map((phone) => <option key={phone.phone_id} value={phone.phone_id}>{phone.phone_name}</option>)}</select></label>; }
function CompareProduct({ phone, winner }: { phone: FinderPhone; winner: boolean }) { const rows = [phone.score.overall, phone.score.sentiment, phone.score.aspect_fit, phone.score.complaint_safety, phone.score.evidence]; return <article className={winner ? "compare-product winner" : "compare-product"}><div className="compare-product-head">{winner && <span>Recommended</span>}<div className="compare-image">{phone.image_url && <img src={phone.image_url} alt="" />}</div><small>{phone.brand}</small><h2>{phone.phone_name}</h2></div><div className="compare-values">{rows.map((value, index) => <span key={index}><strong>{value.toFixed(1)}</strong><ScoreBar value={value} tone={winner ? "green" : "cyan"} /></span>)}<span><strong>{phone.review_count.toLocaleString()}</strong></span><span><strong>{money(phone.best_price)}</strong></span></div></article>; }

function Intelligence() {
  const brands = rawData.competitive.brands; const maxReviews = Math.max(...brands.map((brand) => brand.reviews)); const evidenceLeader = [...brands].sort((a,b) => b.reviews-a.reviews)[0];
  return <><WorkspaceHeader eyebrow="Competitive intelligence" title="See where the market is moving." summary="A brand-level read of advocacy, risk, evidence strength and the customer themes shaping competitive position." meta={`${brands.length} brands benchmarked`} /><section className="metric-grid compact-metrics"><MetricCard label="Market average" value={pct(rawData.competitive.market_average)} detail="Positive customer signal" /><MetricCard label="Category leader" value={brands[0].brand} detail={`${pct(brands[0].positive_percent)} positive`} tone="green" /><MetricCard label="Largest evidence base" value={evidenceLeader.brand} detail={`${evidenceLeader.reviews.toLocaleString()} reviews`} tone="violet" /><MetricCard label="Brands tracked" value={String(brands.length)} detail="Across five price bands" tone="amber" /></section><section className="benchmark-panel"><div className="panel-heading"><div><span className="section-kicker">Market benchmark</span><h2>Brand position by customer advocacy</h2></div><span className="legend"><i /> positive signal <b /> evidence volume</span></div><div className="brand-table"><div className="brand-table-head"><span>Brand</span><span>Advocacy</span><span>Evidence</span><span>Strength</span><span>Primary concern</span></div>{brands.map((brand, index) => <div className="brand-row" key={brand.brand}><span><b>{String(index + 1).padStart(2,"0")}</b><strong>{brand.brand}</strong><small>{brand.phones} phones</small></span><span><strong>{pct(brand.positive_percent)}</strong><ScoreBar value={brand.positive_percent} tone="green" /></span><span><strong>{brand.reviews.toLocaleString()}</strong><ScoreBar value={brand.reviews / maxReviews * 100} tone="violet" /></span><span className="text-cell">{brand.top_strength}</span><span className="text-cell risk-text">{brand.top_concern}</span></div>)}</div></section></>;
}

function Actions() {
  const [priority, setPriority] = useState("All");
  const priorityItems = ["All", ...["Critical", "Important", "Monitor"].filter((item) => rawData.actions.some((action) => action.priority === item))];
  const actions = rawData.actions.filter((action) => priority === "All" || action.priority === priority);
  return <><WorkspaceHeader eyebrow="Action center" title="Turn evidence into a roadmap." summary="Prioritized experience themes connect customer friction to the teams best placed to investigate and improve it." meta={`${rawData.actions.length} opportunity areas`} /><section className="action-toolbar"><Segmented items={priorityItems} active={priority} onChange={setPriority} /><span>Priority reflects negative mentions and cross-product reach.</span></section><section className="action-list">{actions.map((action) => <article className="action-row" key={action.id}><span className="action-id">{action.id}</span><span className={`priority ${action.priority.toLowerCase()}`}>{action.priority}</span><div className="action-copy"><small>{action.aspect} · {action.owner}</small><strong>{action.recommendation}</strong></div><div className="action-stat"><strong>{action.mentions.toLocaleString()}</strong><small>negative mentions</small></div><div className="action-stat"><strong>{action.phones}</strong><small>phones affected</small></div><a href={`/reviews?q=${encodeURIComponent(action.aspect)}`} aria-label={`Inspect evidence for ${action.aspect}`}>↗</a></article>)}{!actions.length && <p className="empty-state">No opportunity areas currently carry this priority.</p>}</section></>;
}

export function Workspace({ mode }: { mode: Mode }) { if (mode === "overview") return <Overview />; if (mode === "phones") return <DetailedPhones />; if (mode === "reviews") return <DetailedReviews />; if (mode === "finder") return <DetailedFinder />; if (mode === "compare") return <DetailedCompare />; if (mode === "intelligence") return <IntelligenceWorkspace />; return <ActionCenter />; }
